name: app_client
description: MyApp
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  device_info_plus: ^10.1.0
flutter:
  uses-material-design: true
dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.8

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icon.png"

flutter_native_splash:
  color: "#000000"
  image: "splash.png"
  android: true
  ios: true
